#!/bin/sh
# crt0o's bspwm config

# --- Monitor setup ---
# TODO: Modify to fit your setup
xrandr --auto
# xrandr --output eDP-1-1 --right-of HDMI-0

# --- Keyboard layout ---
# TODO: Modify to fit your setup
# setxkbmap si

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# --- Desktops ---
# TODO: Modify to fit your setup
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# bspc monitor HDMI-0 -d 1 3 4 5 6 7 8 9 10
# bspc monitor eDP-1-1 -d 2

# --- Window settings ---
bspc config border_width         5
bspc config window_gap          15
bspc config focused_border_color "#9a765e"

bspc config normal_border_color "#0d1015"
bspc config active_border_color "#0d1015" 

bspc config remove_disabled_monitors true
bspc config split_ratio          0.61
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# --- Other tasks ---

# Draw background
feh --bg-scale ${HOME}/Backgrounds/background.*

# Start picom
picom --experimental-backends &
